project:
  type: book
  output-dir: docs

book:
  title: "Data Jobs Done With R"
  author: "Lingyun Zhang"
  date: today
  date-format: YYYY-MM-DD
  chapters:
    - index.qmd
    - get_data_into_R.qmd
    - explore_data.qmd
    - data_manipulation.qmd
    - output_results.qmd

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]

editor: visual

